//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: light framework (CF/Silverlight) enabled
    
// Generated from: foo.proto
namespace foo
{
  [global::ProtoBuf.ProtoContract(Name=@"Foo")]
  public partial class Foo : global::AqlaSerializer.IExtensible
  {
    public Foo() {}
    

    private int _bar = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bar
    {
      get { return _bar; }
      set { _bar = value; }
    }
    private global::AqlaSerializer.IExtension extensionObject;
    global::AqlaSerializer.IExtension global::AqlaSerializer.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::AqlaSerializer.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
